grid:
  - '0'
  - '1'
  - '2'
  - '3'

stages:
  train:
    '0':
      script: scripts/train.py
      params:
        max_depth: 5
        labels_path: 'data/output/prepare_data/0_target.csv'
        data_path: 'data/input/features.csv'
        model_path: 'data/output/models/0_model.pickle'
        metrics_path: 'data/output/metrics/0_metrics.yaml'
    '1':
      script: scripts/train.py
      params:
        max_depth: 5
        labels_path: 'data/output/prepare_data/1_target.csv'
        data_path: 'data/input/features.csv'
        model_path: 'data/output/models/1_model.pickle'
        metrics_path: 'data/output/metrics/1_metrics.yaml'
    '2':
      script: scripts/train.py
      params:
        max_depth: 20
        labels_path: 'data/output/prepare_data/2_target.csv'
        data_path: 'data/input/features.csv'
        model_path: 'data/output/models/2_model.pickle'
        metrics_path: 'data/output/metrics/2_metrics.yaml'
    '3':
      script: scripts/train.py
      params:
        max_depth: 20
        labels_path: 'data/output/prepare_data/3_target.csv'
        data_path: 'data/input/features.csv'
        model_path: 'data/output/models/3_model.pickle'
        metrics_path: 'data/output/metrics/3_metrics.yaml'


